### ISSUE TITLE
[버그] 회원가입이 안되요ㅜㅠ

### ISSUE THREAD

**Issue by Lahavas** [wwh-techcamp-2018/team1-WannaOne#122]
<img width="1440" alt="2018-08-24 5 09 58" src="https://user-images.githubusercontent.com/16870788/44573057-9464e600-a7c0-11e8-9625-a698aed342de.png">
요거처럼 정상적으로 회원가입 폼을 치고 클릭해도 ajax 콜자체가 안먹힙니다~
비밀번호는 asdfqwer1234

**Comment by kyucumber** [comment]
이거 저희 프로젝트가 아닌거같은데..

**Comment by Lahavas** [comment]
죄송함다ㅜㅠ 클로즈할게요
