### ISSUE TITLE
[버그] 텍스트를 길게 하고 등록하기를 누르면 로그아웃이되요ㅜ

### ISSUE THREAD

**Issue by Lahavas** [wwh-techcamp-2018/team1-WannaOne#126]
<img width="516" alt="2018-08-24 5 13 32" src="https://user-images.githubusercontent.com/16870788/44573263-22d96780-a7c1-11e8-99a2-ff911bb5635b.png">
요렇게 됩니다ㅜㅠ

**Comment by doooyeon** [comment]
저희조 플젝이 아닌데용 ㅠㅠ

**Comment by Lahavas** [comment]
죄송함다ㅜ 클로즈할게요
